### ISSUE TITLE
When I try to parse binary file, an error is thrown

### ISSUE THREAD

**Issue by KaiserKatze** [fge/largetext#4]
```
Exception in thread "main" com.github.fge.largetext.LargeTextException: decoding error
    at com.github.fge.largetext.load.DecodingStatus.getTotalSize(DecodingStatus.java:211)
    at com.github.fge.largetext.load.TextDecoder.getTotalChars(TextDecoder.java:172)
    at com.github.fge.largetext.LargeText.length(LargeText.java:129)
    at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
    at java.util.regex.Matcher.reset(Matcher.java:309)
    at java.util.regex.Matcher.<init>(Matcher.java:229)
    at java.util.regex.Pattern.matcher(Pattern.java:1093)
    at com.stellaris.Stellaris.getGameVersion(Stellaris.java:93)
    at com.stellaris.Stellaris.main(Stellaris.java:226)
Caused by: java.io.IOException: unable to read file as text starting from byte offset 2
    at com.github.fge.largetext.load.TextDecoder$1.run(TextDecoder.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by fge** [comment]
This is perfectly normal... Largetext is meant to read text data only.
